# Generated by Django 4.2.27 on 2026-04-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0044_userprofile_cancel_at_cycle_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_reminder',
            field=models.BooleanField(default=True, verbose_name='Daily Expense Reminder'),
        ),
    ]
