# Generated by Django 4.2.27 on 2026-04-17 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0045_userprofile_daily_reminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Family Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_families', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='is_shared',
            field=models.BooleanField(default=False, verbose_name='Shared with Family'),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_shared',
            field=models.BooleanField(default=False, verbose_name='Shared with Family'),
        ),
        migrations.AddField(
            model_name='income',
            name='is_shared',
            field=models.BooleanField(default=False, verbose_name='Shared with Family'),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='is_shared',
            field=models.BooleanField(default=False, verbose_name='Shared with Family'),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='is_shared',
            field=models.BooleanField(default=False, verbose_name='Shared with Family'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='is_shared',
            field=models.BooleanField(default=False, verbose_name='Shared with Family'),
        ),
        migrations.CreateModel(
            name='FamilyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='expenses.family')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='expenses.family', verbose_name='Family'),
        ),
        migrations.AddField(
            model_name='expense',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.family', verbose_name='Family'),
        ),
        migrations.AddField(
            model_name='income',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='expenses.family', verbose_name='Family'),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_transactions', to='expenses.family', verbose_name='Family'),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_goals', to='expenses.family', verbose_name='Family'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='expenses.family', verbose_name='Family'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='expenses.family', verbose_name='Family'),
        ),
    ]
