# Generated by Django 4.2.27 on 2026-05-21 14:26

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0053_recurringtransaction_loan_type_and_fk'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', 'source_type', 'status'], name='expenses_jo_user_id_cebd3b_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='journalentry_metadata_gin'),
        ),
    ]
