# Generated by Django 4.2.27 on 2026-05-25 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0054_add_journalentry_composite_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='salary_date',
            field=models.IntegerField(default=1, help_text='Day of month when salary is received (1-31). Default is 1st of every month.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
