# Generated by Django 4.2.27 on 2026-06-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0056_convert_reversed_to_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='consent_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='consent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='consent_version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income'), ('TRANSFER', 'Transfer'), ('LOAN_REPAYMENT', 'Loan Repayment'), ('GOAL_CONTRIBUTION', 'Goal Contribution'), ('ADJUSTMENT', 'Adjustment')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ledgerpostingfailure',
            name='source_type',
            field=models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income'), ('TRANSFER', 'Transfer'), ('LOAN_REPAYMENT', 'Loan Repayment'), ('GOAL_CONTRIBUTION', 'Goal Contribution'), ('ADJUSTMENT', 'Adjustment')], max_length=30),
        ),
    ]
