# Generated by Django 4.2.27 on 2026-06-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0057_userprofile_consent_granted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionRequestAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=150)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
