# Generated by Django 4.2.27 on 2026-06-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0059_capitalevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='capitalevent',
            new_name='expenses_ca_user_id_2499bc_idx',
            old_name='expenses_ca_user_id_date_idx',
        ),
        migrations.RenameIndex(
            model_name='capitalevent',
            new_name='expenses_ca_user_id_6538df_idx',
            old_name='expenses_ca_user_id_subtype_idx',
        ),
        migrations.RenameIndex(
            model_name='capitalevent',
            new_name='expenses_ca_linked__17c15b_idx',
            old_name='expenses_ca_linked_loan_idx',
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='capital_subtype',
            field=models.CharField(blank=True, choices=[('loan_down_payment', 'Loan Down Payment'), ('loan_prepayment', 'Loan Prepayment'), ('large_purchase', 'Large Purchase'), ('medical_lump_sum', 'Medical Lump Sum'), ('gift_given', 'Gift Given'), ('gift_received', 'Gift Received'), ('investment_lump_sum', 'Investment Lump Sum'), ('other', 'Other')], max_length=30, null=True, verbose_name='Capital Event Subtype'),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='exclude_from_averages',
            field=models.BooleanField(default=True, verbose_name='Exclude from Averages & Trends'),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='exclude_from_budget',
            field=models.BooleanField(default=True, verbose_name='Exclude from Budget'),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='include_in_net_worth',
            field=models.BooleanField(default=True, verbose_name='Include in Cash Flow / Net Worth'),
        ),
        migrations.AlterField(
            model_name='ledgerpostingfailure',
            name='source_type',
            field=models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income'), ('TRANSFER', 'Transfer'), ('LOAN_REPAYMENT', 'Loan Repayment'), ('GOAL_CONTRIBUTION', 'Goal Contribution'), ('ADJUSTMENT', 'Adjustment'), ('CAPITAL_EVENT', 'Capital Event')], max_length=30),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income'), ('TRANSFER', 'Transfer'), ('LOAN', 'Loan Repayment'), ('CAPITAL', 'Capital Event')], max_length=10, verbose_name='Transaction Type'),
        ),
    ]
