# Generated by Django 4.2.27 on 2026-06-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0060_rename_expenses_ca_user_id_date_idx_expenses_ca_user_id_2499bc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
    ]
