# Generated by Django 4.2.27 on 2026-06-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0061_recurringtransaction_end_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recurringtransaction',
            name='unique_recurring_transaction',
        ),
        migrations.AddConstraint(
            model_name='recurringtransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'transaction_type', 'amount', 'currency', 'description', 'frequency', 'start_date'), name='unique_recurring_transaction'),
        ),
    ]
