# Generated by Django 4.2.27 on 2026-07-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0062_remove_recurringtransaction_unique_recurring_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='source_type',
            field=models.CharField(blank=True, choices=[('Salary', 'Salary'), ('Freelance / Consulting', 'Freelance / Consulting'), ('Business', 'Business'), ('Investment Returns', 'Investment Returns'), ('Rental Income', 'Rental Income'), ('Cashback & Rewards', 'Cashback & Rewards'), ('Refund / Reimbursement', 'Refund / Reimbursement'), ('Other', 'Other')], max_length=50, null=True, verbose_name='Source Type'),
        ),
    ]
