# Generated by Django 4.2.27 on 2026-07-03 14:03

import difflib
from django.db import migrations

CHOICES = [
    'Salary',
    'Freelance / Consulting',
    'Business',
    'Investment Returns',
    'Rental Income',
    'Cashback & Rewards',
    'Refund / Reimbursement',
    'Other'
]

def map_source_to_type(source_str):
    if not source_str:
        return 'Other'
    
    source_clean = source_str.strip().lower()
    
    # Direct case-insensitive / substring checks first for common patterns
    if 'salary' in source_clean or 'stipend' in source_clean or 'wages' in source_clean:
        return 'Salary'
    if 'freelance' in source_clean or 'consulting' in source_clean or 'gigs' in source_clean:
        return 'Freelance / Consulting'
    if 'business' in source_clean or 'profits' in source_clean or 'sales' in source_clean:
        return 'Business'
    if 'dividend' in source_clean or 'interest' in source_clean or 'investment' in source_clean or 'stock' in source_clean or 'crypto' in source_clean or 'fd' in source_clean or 'mutual fund' in source_clean:
        return 'Investment Returns'
    if 'rent' in source_clean or 'rental' in source_clean or 'sublet' in source_clean:
        return 'Rental Income'
    if 'cashback' in source_clean or 'rewards' in source_clean or 'reward' in source_clean or 'coupon' in source_clean or 'points' in source_clean:
        return 'Cashback & Rewards'
    if 'refund' in source_clean or 'reimbursement' in source_clean or 'reimburse' in source_clean:
        return 'Refund / Reimbursement'
        
    # Case-insensitive match on the choices directly
    for choice in CHOICES:
        if choice.lower() in source_clean or source_clean in choice.lower():
            if choice == 'Other':
                continue
            return choice
            
    # Fuzzy matching using difflib
    candidates = [c for c in CHOICES if c != 'Other']
    close_matches = difflib.get_close_matches(source_clean, [c.lower() for c in candidates], n=1, cutoff=0.6)
    if close_matches:
        matched_lower = close_matches[0]
        for choice in candidates:
            if choice.lower() == matched_lower:
                return choice
                
    return 'Other'

def map_sources(apps, schema_editor):
    Income = apps.get_model('expenses', 'Income')
    for income in Income.objects.all():
        income.source_type = map_source_to_type(income.source)
        income.save(update_fields=['source_type'])

def unmap_sources(apps, schema_editor):
    Income = apps.get_model('expenses', 'Income')
    for income in Income.objects.all():
        income.source_type = None
        income.save(update_fields=['source_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0063_add_source_type_nullable'),
    ]

    operations = [
        migrations.RunPython(map_sources, unmap_sources),
    ]
