# Generated by Django 4.2.27 on 2026-07-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0064_map_income_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='source_type',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Freelance / Consulting', 'Freelance / Consulting'), ('Business', 'Business'), ('Investment Returns', 'Investment Returns'), ('Rental Income', 'Rental Income'), ('Cashback & Rewards', 'Cashback & Rewards'), ('Refund / Reimbursement', 'Refund / Reimbursement'), ('Other', 'Other')], default='Salary', max_length=50, verbose_name='Source Type'),
        ),
    ]
