# Generated by Django 4.2.27 on 2026-07-07

import uuid
from django.db import migrations, models

def populate_uuids(apps, schema_editor):
    models_to_migrate = [
        'Account', 'Loan', 'Expense', 'Income', 'Category', 'Transfer',
        'RecurringTransaction', 'SavingsGoal', 'GoalContribution',
        'CapitalEvent', 'LoanRepayment', 'Notification'
    ]
    for model_name in models_to_migrate:
        Model = apps.get_model('expenses', model_name)
        for obj in Model.objects.filter(uuid__isnull=True):
            obj.uuid = uuid.uuid4()
            obj.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0065_alter_source_type_nonnullable'),
    ]

    operations = [
        # Step 1: Add UUID field as nullable
        migrations.AddField(
            model_name='account',
            name='uuid',
            field=models.UUIDField(null=True, blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='uuid',
            field=models.UUIDField(null=True, blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='uuid',
            field=models.UUIDField(null=True, blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='income',
            name='uuid',
            field=models.UUIDField(null=True, blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(null=True, blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='transfer',
            name='uuid',
            field=models.UUIDField(null=True, blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='uuid',
            field=models.UUIDField(null=True, blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='uuid',
            field=models.UUIDField(null=True, blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='goalcontribution',
            name='uuid',
            field=models.UUIDField(null=True, blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='capitalevent',
            name='uuid',
            field=models.UUIDField(null=True, blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='uuid',
            field=models.UUIDField(null=True, blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='uuid',
            field=models.UUIDField(null=True, blank=True, editable=False),
        ),

        # Step 2: Populate distinct UUID values for existing rows
        migrations.RunPython(populate_uuids, reverse_code=migrations.RunPython.noop),

        # Step 3: Alter field to unique=True and non-nullable
        migrations.AlterField(
            model_name='account',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
        migrations.AlterField(
            model_name='income',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
        migrations.AlterField(
            model_name='goalcontribution',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
        migrations.AlterField(
            model_name='capitalevent',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
    ]
