# Generated by Django 4.2.27 on 2026-07-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0066_add_uuid_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['user', 'is_active'], name='expenses_re_user_id_3e7cec_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['user', 'date'], name='expenses_tr_user_id_5e28dc_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['user', 'to_account'], name='expenses_tr_user_id_c1007e_idx'),
        ),
    ]
