# Generated by Django 4.2.27 on 2026-07-13 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0067_add_transfer_recurringtx_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('as_of_date', models.DateField(default=django.utils.timezone.now)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-as_of_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('purpose', models.CharField(blank=True, max_length=100, null=True)),
                ('consent_version', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FXRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(choices=[('₹', 'Indian Rupee (₹)'), ('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('£', 'Pound Sterling (£)'), ('¥', 'Japanese Yen (¥)'), ('A$', 'Australian Dollar (A$)'), ('C$', 'Canadian Dollar (C$)'), ('CHF', 'Swiss Franc (CHF)'), ('元', 'Chinese Yuan (元)'), ('₩', 'South Korean Won (₩)')], max_length=5)),
                ('to_currency', models.CharField(choices=[('₹', 'Indian Rupee (₹)'), ('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('£', 'Pound Sterling (£)'), ('¥', 'Japanese Yen (¥)'), ('A$', 'Australian Dollar (A$)'), ('C$', 'Canadian Dollar (C$)'), ('CHF', 'Swiss Franc (CHF)'), ('元', 'Chinese Yuan (元)'), ('₩', 'South Korean Won (₩)')], max_length=5)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=15)),
                ('as_of_date', models.DateField(default=django.utils.timezone.now)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('instrument_name', models.CharField(max_length=255)),
                ('instrument_type', models.CharField(choices=[('MF', 'Mutual Fund'), ('STOCK', 'Stock'), ('NPS', 'NPS'), ('PPF', 'PPF'), ('EPF', 'EPF'), ('RD', 'Recurring Deposit'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('units', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('avg_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(choices=[('₹', 'Indian Rupee (₹)'), ('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('£', 'Pound Sterling (£)'), ('¥', 'Japanese Yen (¥)'), ('A$', 'Australian Dollar (A$)'), ('C$', 'Canadian Dollar (C$)'), ('CHF', 'Swiss Franc (CHF)'), ('元', 'Chinese Yuan (元)'), ('₩', 'South Korean Won (₩)')], default='₹', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanScheduleInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_no', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('scheduled_principal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('scheduled_interest', models.DecimalField(decimal_places=2, max_digits=15)),
                ('scheduled_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='NetWorthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField(default=django.utils.timezone.now)),
                ('total_net_worth', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_assets', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_liabilities', models.DecimalField(decimal_places=2, max_digits=15)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('asset_class', models.CharField(choices=[('REAL_ESTATE', 'Real Estate'), ('VEHICLE', 'Vehicle'), ('GOLD', 'Gold/Jewelry'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('acquisition_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('₹', 'Indian Rupee (₹)'), ('$', 'US Dollar ($)'), ('€', 'Euro (€)'), ('£', 'Pound Sterling (£)'), ('¥', 'Japanese Yen (¥)'), ('A$', 'Australian Dollar (A$)'), ('C$', 'Canadian Dollar (C$)'), ('CHF', 'Swiss Franc (CHF)'), ('元', 'Chinese Yuan (元)'), ('₩', 'South Korean Won (₩)')], default='₹', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('as_of_date', models.DateField(default=django.utils.timezone.now)),
                ('unit_nav', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-as_of_date', '-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='expense',
            name='unique_expense',
        ),
        migrations.RemoveConstraint(
            model_name='income',
            name='unique_income',
        ),
        migrations.AddField(
            model_name='expense',
            name='category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.category', verbose_name='Category FK'),
        ),
        migrations.AddField(
            model_name='expense',
            name='client_dedup_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Client Deduplication Key'),
        ),
        migrations.AddField(
            model_name='income',
            name='client_dedup_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Client Deduplication Key'),
        ),
        migrations.AddField(
            model_name='income',
            name='source_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='expenses.category', verbose_name='Source FK'),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_transactions', to='expenses.category', verbose_name='Category FK'),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='ledger_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='expenses.ledgeraccount'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(condition=models.Q(('client_dedup_key__isnull', False)), fields=['user', 'client_dedup_key'], name='idx_expense_client_dedup'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(condition=models.Q(('client_dedup_key__isnull', False)), fields=['user', 'client_dedup_key'], name='idx_income_client_dedup'),
        ),
        migrations.AddField(
            model_name='valuation',
            name='holding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='expenses.holding'),
        ),
        migrations.AddField(
            model_name='physicalasset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='networthsnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='net_worth_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanscheduleinstallment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_installments', to='expenses.loan'),
        ),
        migrations.AddField(
            model_name='holding',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='expenses.account'),
        ),
        migrations.AddConstraint(
            model_name='fxrate',
            constraint=models.UniqueConstraint(fields=('from_currency', 'to_currency', 'as_of_date'), name='unique_fx_rate'),
        ),
        migrations.AddField(
            model_name='consentevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetvaluation',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='expenses.physicalasset'),
        ),
        migrations.AddIndex(
            model_name='networthsnapshot',
            index=models.Index(fields=['user', 'as_of_date'], name='expenses_ne_user_id_0b1d7e_idx'),
        ),
        migrations.AddConstraint(
            model_name='networthsnapshot',
            constraint=models.UniqueConstraint(fields=('user', 'as_of_date'), name='unique_net_worth_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='loanscheduleinstallment',
            constraint=models.UniqueConstraint(fields=('loan', 'installment_no'), name='unique_loan_installment'),
        ),
    ]
