# Generated by Django 4.2.27 on 2026-07-13 13:11

from django.db import migrations


import uuid

def forward_func(apps, schema_editor):
    Expense = apps.get_model('expenses', 'Expense')
    Income = apps.get_model('expenses', 'Income')
    RecurringTransaction = apps.get_model('expenses', 'RecurringTransaction')
    Category = apps.get_model('expenses', 'Category')

    # Expenses
    for expense in Expense.objects.filter(category__isnull=False).exclude(category=''):
        category_obj, _ = Category.objects.get_or_create(
            user=expense.user,
            name=expense.category.strip(),
            defaults={'uuid': uuid.uuid4()}
        )
        expense.category_fk = category_obj
        expense.save(update_fields=['category_fk'])

    # Incomes
    for income in Income.objects.filter(source__isnull=False).exclude(source=''):
        category_obj, _ = Category.objects.get_or_create(
            user=income.user,
            name=income.source.strip(),
            defaults={'uuid': uuid.uuid4()}
        )
        income.source_fk = category_obj
        income.save(update_fields=['source_fk'])

    # RecurringTransactions
    for rt in RecurringTransaction.objects.filter(category__isnull=False).exclude(category=''):
        category_obj, _ = Category.objects.get_or_create(
            user=rt.user,
            name=rt.category.strip(),
            defaults={'uuid': uuid.uuid4()}
        )
        rt.category_fk = category_obj
        rt.save(update_fields=['category_fk'])

class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0068_assetvaluation_consentevent_fxrate_holding_and_more'),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_code=migrations.RunPython.noop),
    ]
