# Generated by Django 4.2.27 on 2026-07-13 13:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0070_capitalevent_deleted_at_capitalevent_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Monthly Limit'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Amount in Base Currency'),
        ),
        migrations.AlterField(
            model_name='goalcontribution',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Contribution Amount'),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='income',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Amount in Base Currency'),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Amount Paid (EMI)'),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Amount in Base Currency'),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='interest_portion',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Interest Portion'),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='principal_portion',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Principal Portion'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Amount in Base Currency'),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Current Amount'),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Target Amount'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in INR', max_digits=15),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='converted_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Amount in Base Currency'),
        ),
    ]
