# Generated by Django 4.2.27 on 2026-07-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0071_alter_category_limit_alter_expense_amount_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expense',
            name='idx_expense_client_dedup',
        ),
        migrations.RemoveIndex(
            model_name='income',
            name='idx_income_client_dedup',
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(condition=models.Q(('client_dedup_key__isnull', False)), fields=('user', 'client_dedup_key'), name='idx_expense_client_dedup'),
        ),
        migrations.AddConstraint(
            model_name='income',
            constraint=models.UniqueConstraint(condition=models.Q(('client_dedup_key__isnull', False)), fields=('user', 'client_dedup_key'), name='idx_income_client_dedup'),
        ),
    ]
