# Generated by Django 4.2.27 on 2026-07-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0072_remove_expense_idx_expense_client_dedup_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'account'], name='expenses_ex_user_id_25617c_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['user', 'account'], name='expenses_in_user_id_b58073_idx'),
        ),
    ]
