# Generated by Django 4.2.27 on 2026-07-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0073_expense_expenses_ex_user_id_25617c_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['user', 'from_account'], name='expenses_tr_user_id_828e0d_idx'),
        ),
    ]
