# Generated by Django 4.2.27 on 2026-07-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0075_account_type_expansion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dismissed_onboarding_checklist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='persona',
            field=models.CharField(blank=True, choices=[('SALARIED', 'Salaried professional'), ('FREELANCER', 'Freelancer / Consultant'), ('FAMILY', 'Managing family finances'), ('STUDENT', 'Student / Just starting out')], max_length=20, null=True),
        ),
    ]
