# Generated by Django 4.2.27 on 2026-07-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0076_userprofile_dismissed_onboarding_checklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='client_dedup_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Client Deduplication Key'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.UniqueConstraint(condition=models.Q(('client_dedup_key__isnull', False)), fields=('user', 'client_dedup_key'), name='idx_transfer_client_dedup'),
        ),
    ]
