# Generated by Django 4.2.27 on 2026-07-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0077_transfer_client_dedup_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Cash & Bank', (('CASH_WALLET', 'Cash Wallet'), ('SAVINGS_ACCOUNT', 'Savings Account'), ('SALARY_ACCOUNT', 'Salary Account'), ('CURRENT_ACCOUNT', 'Current Account'), ('DIGITAL_WALLET', 'Digital Wallet (Paytm, Amazon Pay, etc.)'))), ('Fixed-Income', (('FD', 'Fixed Deposit (FD)'), ('RD', 'Recurring Deposit (RD)'), ('PPF', 'Public Provident Fund (PPF)'), ('EPF', "Employees' Provident Fund (EPF)"), ('VPF', 'Voluntary Provident Fund (VPF)'), ('NPS', 'National Pension System (NPS)'), ('SSY', 'Sukanya Samriddhi Yojana (SSY)'), ('POST_OFFICE', 'Post Office Savings (SCSS, NSC, KVP)'), ('APY', 'Atal Pension Yojana (APY)'))), ('Investments', (('DEMAT', 'Demat Account (Direct Equity)'), ('MUTUAL_FUND', 'Mutual Funds'), ('ETF', 'Exchange Traded Funds (ETF)'), ('SGB', 'Sovereign Gold Bonds (SGB)'), ('ULIP', 'Unit Linked Insurance Plan (ULIP)'), ('GOLD', 'Digital / Physical Gold'))), ('Short-Term Credit', (('CREDIT_CARD', 'Credit Card'), ('BNPL', 'Buy Now Pay Later (BNPL)'), ('OVERDRAFT', 'Overdraft (OD) / Cash Credit (CC)'))), ('Long-Term Loans', (('HOME_LOAN', 'Home Loan'), ('VEHICLE_LOAN', 'Vehicle Loan'), ('EDUCATION_LOAN', 'Education Loan'), ('PERSONAL_LOAN', 'Personal Loan'), ('BUSINESS_LOAN', 'Business Loan'), ('LAP', 'Loan Against Property (LAP)'), ('GOLD_LOAN', 'Gold Loan'))), ('Physical Assets', (('REAL_ESTATE', 'Real Estate'), ('VEHICLE', 'Vehicle'), ('LIFE_INSURANCE', 'Traditional Life Insurance (Surrender Value)'))), ('Legacy', (('CASH', 'Cash (legacy)'), ('BANK', 'Bank Account (legacy)'), ('CREDIT_CARD', 'Credit Card (legacy)'), ('INVESTMENT', 'Investment (legacy)'), ('FIXED_DEPOSIT', 'Fixed Deposit (legacy)'), ('OTHER', 'Other (legacy)')))], default='SAVINGS_ACCOUNT', max_length=32, verbose_name='Account Type'),
        ),
    ]
