# Generated by Django 4.2.27 on 2026-07-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0078_alter_account_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='deposit_maturity_date',
            field=models.DateField(blank=True, null=True, verbose_name='Deposit Maturity Date'),
        ),
    ]
