# Generated by Django 4.2.27 on 2026-07-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0079_account_deposit_maturity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='show_accrued_balance',
            field=models.BooleanField(default=True, help_text='If enabled, the dashboard and account lists will display the projected accrued balance instead of the ledger balance.', verbose_name='Show Accrued Balance'),
        ),
    ]
