# Generated by Django 4.2.27 on 2026-08-04 13:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0080_account_show_accrued_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Credit Limit'),
        ),
        migrations.AddField(
            model_name='account',
            name='deposit_closed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Deposit Closed Date'),
        ),
        migrations.AddField(
            model_name='account',
            name='rd_installment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='RD Installment Amount'),
        ),
        migrations.AddField(
            model_name='account',
            name='rd_installment_day',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='RD Installment Day'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_interest_category',
            field=models.BooleanField(default=False, verbose_name='Is Interest Category'),
        ),
        migrations.AddField(
            model_name='expense',
            name='linked_physical_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.physicalasset', verbose_name='Linked Physical Asset'),
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='cached_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Cached Balance'),
        ),
        migrations.AddField(
            model_name='loan',
            name='repayment_type',
            field=models.CharField(choices=[('EMI', 'EMI Amortizing'), ('BULLET', 'Bullet Repayment'), ('INTEREST_ONLY', 'Interest Only')], default='EMI', max_length=20, verbose_name='Repayment Type'),
        ),
        migrations.AddField(
            model_name='physicalasset',
            name='policy_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Policy Number'),
        ),
        migrations.AddField(
            model_name='physicalasset',
            name='policy_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Policy Start Date'),
        ),
        migrations.AddField(
            model_name='physicalasset',
            name='premium_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Premium Amount'),
        ),
        migrations.AddField(
            model_name='physicalasset',
            name='premium_frequency',
            field=models.CharField(blank=True, choices=[('ANNUAL', 'Annual'), ('SEMI_ANNUAL', 'Semi-Annual'), ('QUARTERLY', 'Quarterly'), ('MONTHLY', 'Monthly')], max_length=20, null=True, verbose_name='Premium Frequency'),
        ),
        migrations.AddField(
            model_name='physicalasset',
            name='sum_assured',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Sum Assured'),
        ),
        migrations.AlterField(
            model_name='physicalasset',
            name='asset_class',
            field=models.CharField(choices=[('REAL_ESTATE', 'Real Estate'), ('VEHICLE', 'Vehicle'), ('GOLD', 'Gold/Jewelry'), ('INSURANCE', 'Insurance Policy'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['linked_physical_asset'], name='expenses_ex_linked__937fb3_idx'),
        ),
    ]
