# Generated by Django 4.2.27 on 2026-08-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0081_account_credit_limit_account_deposit_closed_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='unique_account_per_user',
        ),
        migrations.AlterField(
            model_name='account',
            name='deposit_compounding',
            field=models.CharField(blank=True, choices=[('SIMPLE', 'Simple Interest'), ('QUARTERLY', 'Quarterly Compounding'), ('MONTHLY', 'Monthly Compounding'), ('ANNUAL', 'Annual Compounding')], max_length=10, null=True, verbose_name='Compounding Frequency'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'name'), name='unique_account_per_user'),
        ),
    ]
