# Generated by Django 4.2.27 on 2026-08-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0082_remove_account_unique_account_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='record_maturity_income',
            field=models.BooleanField(default=False, help_text='If enabled, accrued interest is recorded as Income under Investment Returns.', verbose_name='Record Interest Earned as Income'),
        ),
    ]
