# Generated by Django 4.2.27 on 2026-08-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0083_account_record_maturity_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='is_last_day_of_month',
            field=models.BooleanField(default=False, verbose_name='Repeat on last day of month'),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='is_last_working_day',
            field=models.BooleanField(default=False, verbose_name='Repeat on last working day of month'),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-Weekly (Every 2 Weeks)'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly (Every 3 Months)'), ('SEMIANNUALLY', 'Semi-Annually (Every 6 Months)'), ('YEARLY', 'Yearly')], max_length=15, verbose_name='Frequency'),
        ),
    ]
