# Generated by Django 4.2.27 on 2026-08-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0084_recurringtransaction_is_last_day_of_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMFIScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('scheme_name', models.CharField(db_index=True, max_length=255)),
                ('isin', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'AMFI Scheme',
                'verbose_name_plural': 'AMFI Schemes',
            },
        ),
        migrations.CreateModel(
            name='FundNAVCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('scheme_name', models.CharField(blank=True, max_length=255, null=True)),
                ('isin', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('latest_nav', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('nav_as_of_date', models.DateField(blank=True, null=True)),
                ('last_fetch_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_fetch_error', models.TextField(blank=True, null=True)),
                ('consecutive_failure_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fund NAV Cache',
                'verbose_name_plural': 'Fund NAV Caches',
            },
        ),
        migrations.AddField(
            model_name='holding',
            name='isin',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='scheme_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['scheme_code', 'is_active'], name='holding_scheme_active_idx'),
        ),
        migrations.AddIndex(
            model_name='amfischeme',
            index=models.Index(fields=['scheme_name'], name='amfi_scheme_name_idx'),
        ),
    ]
