# Generated by Django 4.2.27 on 2026-08-12 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0085_amfischeme_fundnavcache_holding_isin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='source_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_transactions_as_source', to='expenses.category', verbose_name='Source FK'),
        ),
    ]
