# Generated by Django 4.2.27 on 2026-08-24 13:43

from django.db import migrations, models


def backfill_next_due_date(apps, schema_editor):
    RecurringTransaction = apps.get_model('expenses', 'RecurringTransaction')
    for rt in RecurringTransaction.objects.all():
        rt.save()

class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0086_recurringtransaction_source_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='next_due_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Next Due Date'),
        ),
        migrations.RunPython(backfill_next_due_date, reverse_code=migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='financialauditlog',
            index=models.Index(fields=['user', 'model_name', 'timestamp'], name='auditlog_user_model_idx'),
        ),
        migrations.AddIndex(
            model_name='goalcontribution',
            index=models.Index(fields=['goal', 'date'], name='goalcontrib_goal_date_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrepayment',
            index=models.Index(fields=['loan', 'date'], name='loanrepayment_loan_date_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='notif_user_read_at_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['user', 'is_active', 'transaction_type'], name='rt_user_active_type_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['next_due_date'], name='rt_next_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['user', 'is_active', 'next_due_date'], name='rt_user_active_due_idx'),
        ),
        migrations.AddIndex(
            model_name='savingsgoal',
            index=models.Index(fields=['user', 'is_completed'], name='savingsgoal_user_comp_idx'),
        ),
    ]
