# Generated by Django 4.2.27 on 2026-08-26 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0087_recurringtransaction_next_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='credit_card_billing_day',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='Credit Card Billing Day'),
        ),
    ]
