# Generated by Django 4.2.27 on 2026-08-26 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0088_account_credit_card_billing_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='credit_card_billing_day',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Credit Card Billing Day'),
        ),
    ]
