# Generated by Django 4.2.27 on 2026-08-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0090_backfill_recurringtransaction_next_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Is Pinned'),
        ),
    ]
