# Generated by Django 4.2.27 on 2026-09-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0091_account_is_pinned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Markdown')),
                ('image', models.FileField(blank=True, null=True, upload_to='announcements/%Y/%m/')),
                ('audience', models.CharField(choices=[('ALL', 'All users'), ('PAID', 'Paid tiers'), ('FREE', 'Free tier')], default='ALL', max_length=10)),
                ('send_push', models.BooleanField(default=False)),
                ('send_email', models.BooleanField(default=False)),
                ('show_modal', models.BooleanField(default=False)),
                ('cta_link', models.CharField(blank=True, max_length=500)),
                ('cta_text', models.CharField(blank=True, default='Try it now', max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('QUEUED', 'Queued'), ('SENT', 'Sent')], default='DRAFT', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
