# Generated by Django 4.2.27 on 2026-09-02 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0092_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='physical_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_schedules', to='expenses.physicalasset', verbose_name='Insurance Policy'),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income'), ('TRANSFER', 'Transfer'), ('LOAN', 'Loan Repayment'), ('CAPITAL', 'Capital Event'), ('INSURANCE_PREMIUM', 'Insurance Premium')], max_length=20, verbose_name='Transaction Type'),
        ),
    ]
