# Generated by Django 4.2.27 on 2026-09-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0094_alter_account_account_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', '-date'], name='expense_user_date_idx'),
        ),
    ]
