# Generated by Django 4.2.27 on 2026-10-02 11:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0096_deduplicate_monthly_report_emaillogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='opening_paid_principal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Principal already paid before tracking started (mid-tenure entry).', max_digits=15),
        ),
    ]
