# Generated by Django 4.2.27 on 2026-10-02 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0097_loan_opening_paid_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_key', models.CharField(max_length=64)),
                ('spec', models.JSONField(default=dict)),
                ('idempotency_key', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_flows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlowCreatedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('step_key', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_objects', to='expenses.financialflow')),
            ],
        ),
        migrations.AddIndex(
            model_name='financialflow',
            index=models.Index(fields=['user', 'idempotency_key'], name='expenses_fi_user_id_3b9c05_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialflow',
            constraint=models.UniqueConstraint(fields=('user', 'idempotency_key'), name='unique_flow_idempotency'),
        ),
    ]
