# Generated by Django 4.2.27 on 2026-10-07 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


from django.utils import timezone

def mark_existing_users_completed(apps, schema_editor):
    UserProfile = apps.get_model('expenses', 'UserProfile')
    # All users who have already seen the tutorial (existing users) are marked onboarding completed
    now = timezone.now()
    UserProfile.objects.filter(has_seen_tutorial=True, onboarding_completed_at__isnull=True).update(onboarding_completed_at=now)

def unmark_existing_users_completed(apps, schema_editor):
    # Reversible
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0098_tmr_flows'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OnboardingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.IntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('persona', models.CharField(blank=True, max_length=20, null=True)),
                ('step1_skipped', models.BooleanField(default=False)),
                ('salary_day', models.IntegerField(blank=True, null=True)),
                ('salary_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('balance_now', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('bank_chip', models.CharField(blank=True, max_length=100, null=True)),
                ('auto_log_salary', models.BooleanField(default=True)),
                ('step2_skipped', models.BooleanField(default=False)),
                ('step3_skipped', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_states', to='expenses.account')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_states', to='expenses.expense')),
                ('income', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_states', to='expenses.income')),
                ('recurring_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_states', to='expenses.recurringtransaction')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=80)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'event', 'created_at'], name='onboarding_evt_user_idx'), models.Index(fields=['event', 'created_at'], name='onboarding_evt_name_idx')],
            },
        ),
        migrations.RunPython(mark_existing_users_completed, unmark_existing_users_completed),
    ]
