# Generated by Django 4.2.27 on 2026-10-08 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0099_onboarding_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseKeywordHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=60)),
                ('category', models.CharField(blank=True, default='', max_length=255)),
                ('payment_method', models.CharField(blank=True, default='', max_length=50)),
                ('use_count', models.PositiveIntegerField(default=1)),
                ('last_used', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='expenses.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_keyword_hints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-last_used'], name='kwhint_user_recent_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='expensekeywordhint',
            constraint=models.UniqueConstraint(fields=('user', 'keyword'), name='unique_expense_keyword_hint'),
        ),
    ]
